---
- name: Install libvirt packages
  package:
    name:
      - libvirt
      - qemu-kvm
    state: present

- name: Start libvirtd
  service:
    name: libvirtd
    state: started
    enabled: yes
