---
- name: Install network-scripts
  package:
    name: network-scripts
    state: present

- name: Install dhcp-client
  package:
    name: dhcp-client
    state: present

- name: Remove default network scripts
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/etc/sysconfig/network-scripts/ifcfg-ens3"
    - "/etc/sysconfig/network-scripts/ifcfg-ens3-1"

- name: Enable network service
  service:
    name: network
    state: started
    enabled: yes
