---
- name: Define network bridge {{ bridge.name }}
  template:
    src: ifcfg-br.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ bridge.name }}"
  register: br

- name: Define network bridge interface {{ bridge.int }}
  template:
    src: ifcfg-int.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ bridge.int }}"
  register: int
  when: bridge.int is defined

- name: Restart networking
  service:
    name: network
    state: restarted
  when: br.changed or int.changed

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
  when: br.changed or int.changed
