---
- name: Define network bridge {{ bridge.name }} and set dns
  template:
    src: ifcfg-br.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ bridge.name }}"
  register: br

- name: Define network bridge interface {{ bridge.int }}
  template:
    src: ifcfg-int.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ bridge.int }}"
  register: int

- name: Restart networking
  service:
    name: network
    state: restarted
  when: br.changed or int.changed
